# An element may not be composed (directly or indirectly) of itself. In other words, the composition relationship must form a strict hierarchy without cycles.

PREFIX archimate: <http://www.opengroup.org/xsd/archimate/3.0/#>

SELECT ?x WHERE {
  ?x archimate:Composition+ ?x .
}
